### ISSUE TITLE
is not 5.0-compatible?

### ISSUE THREAD

**Issue by bitwolaiye** [evadne/RAPageViewController#5]

**Comment by bitwolaiye** [comment]
I merge this project with PSTCollectionView (https://github.com/steipete/PSTCollectionView )
code in my repo https://github.com/bitwolaiye/RAPageViewController
thanks to evadne.

**Comment by jstart** [comment]
:+1: should be merged to support 5.0

**Comment by evadne** [comment]
Yay @bitwolaiye @jstart — thank you all!

I’ll take a look and merge.

**Comment by evadne** [comment]
Took a look. I have several concerns and wish to discuss with you:
- The code is hard coded against PSTCollectionView and will therefore not use UICollectionView on iOS 6. I’m unsure if this is the best course of action.
- If somebody drops the project as it is on https://github.com/bitwolaiye/RAPageViewController/commit/a6ca6743228b42e6141615a70de369838e272239 in their app, they must not have PSTCollectionView already included in the project. Otherwise, there will be duplicate symbols and the linker will refuse to link.

I think — initially — we can do some typedef-fing for every symbol around `UICollectionView` and then run this logic at runtime:
- If there is UICollectionView, use it. Inject the correct values.
- Otherwise, if there is PSTCollectionView, use it, and inject pointers to classes in this library.
- Otherwise, throw in the towel and `abort()`.

It appears that [`PSTCreateUICollectionViewClasses()`](https://github.com/steipete/PSTCollectionView/blob/master/PSTCollectionView/PSTCollectionView.m#L2174) does roughly the same thing. I’ll greatly appreciate if you can try this path — run `RAPageViewController` unmodified, compile with iOS 6.0 SDK with distribution target of iOS 5.0+ to steal all the constants at compile time, and invoke `PSTCreateUICollectionViewClasses()` at run time.

Let me know how it goes.

**Comment by bitwolaiye** [comment]
You are right. Thank you.I will try later

**Comment by evadne** [comment]
Ideally we do not have to change anything in RAPageViewController, but it seems that UIKit compatibility in PSTCollectionView is done by forcing use of special classes from the calling site.

I think it’s because otherwise classes will just not be linked correctly if they are not available. (note: fuzzy memory, I can be dead wrong.)

We might have to implement our own mechanism like that and special-code the sniffing in. Can’t have developers who use RAPageViewController to just fork and patch.
